AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy a service on AWS Fargate, hosted in a private subnet, but accessible via a public load balancer.
Parameters:
  ImageRepoName:
    Type: String
    Default: codemill-docker.jfrog.io/accurate-player/accurate-analyze
    Description: The ecr repo and tag to use for image deployment
  ImageTag:
    Type: String
    Default: 1.2.2
    Description: The ecr repo and tag to use for image deployment
  ContainerCpu:
    Type: Number
    Default: 256
    Description: How much CPU to give the container. 1024 is 1 CPU
  ContainerMemory:
    Type: Number
    Default: 512
    Description: How much memory in megabytes to give the container
  DesiredCount:
    Type: Number
    Default: 2
    Description: How many copies of the service task to run
  ApplicationTag:
    Type: String
    Default: "accurate-video"
  ApAnalyzeCacheDays:
    Type: String
    Default: "5"
    Description: Number of days
  ApAnalyzeCacheDir:
    Type: String
    Default: "/tmp/wav"
    Description: ""
  QuarkusHttpCors:
    Type: String
    Default: "true"
    Description: ""
  Vpc:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID"
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "Private Subnets"
  PublicLoadbalancerListenerArn:
    Type: String
    Description: "Public Loadbalancer Listener Arn"
  LogGroupName:
    Type: String
    Description: "CloudWatch Log Group Name"
  AnalyzeSG:
    Type: AWS::EC2::SecurityGroup::GroupName
    Description: "Analyze Security Group"
  PrivateDNSNamespace:
    Type: String
    Description: "Private DNS Namespace"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Service configuration"
        Parameters:
          - ContainerCpu
          - ContainerMemory
          - DesiredCount
          - Vpc
          - PrivateSubnets
          - PublicLoadbalancerListenerArn
          - LogGroupName
          - AnalyzeSG
          - PrivateDNSNamespace
      - Label:
          default: "Image configuration"
        Parameters:
          - ImageRepoName
          - ImageTag
      - Label:
          default: "...configuration"
        Parameters:
          - ApAnalyzeCacheDays
          - ApAnalyzeCacheDir
          - QuarkusHttpCors
      - Label:
          default: "Other"
        Parameters:
          - ApplicationTag

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: av-analyze
      Cpu: !Ref "ContainerCpu"
      Memory: !Ref "ContainerMemory"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: av-analyze
          Cpu: !Ref "ContainerCpu"
          Memory: !Ref "ContainerMemory"
          Image: !Sub ${ImageRepoName}:${ImageTag}
          PortMappings:
            - ContainerPort: 8080
            - ContainerPort: 5700
            - ContainerPort: 5701
            - ContainerPort: 5702
          Command:
            - "mkdir /tmp/wav && java -jar accurate-analyze.jar"
          EntryPoint:
            - "sh"
            - "-c"
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: !Ref LogGroupName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: av-analyze
          WorkingDirectory: "/opt/"
          Environment:
            - Name: AP_ANALYZE_CACHE_DAYS
              Value: !Ref ApAnalyzeCacheDays
            - Name: AP_ANALYZE_CACHE_DIR
              Value: !Ref ApAnalyzeCacheDir
            - Name: QUARKUS_HTTP_CORS
              Value: !Ref QuarkusHttpCors
            - Name: HTTP_PATH_PREFIX
              Value: "/api"
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  # This is a role which is used by the ECS tasks themselves.
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Path: /
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:BatchGetImage"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:GetAuthorizationToken"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroupName}:*
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:HeadObject"
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: "*"
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  # The service. The service is a resource which allows you to run multiple
  # copies of a type of task, and gather up their logs and metrics, as well
  # as monitor the number of running tasks and replace any that have crashed
  DiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: Discovery Service for the Demo Application
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
          - TTL: 60
            Type: SRV
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: av-analyze
      NamespaceId: !Ref PrivateDNSNamespace
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  # The service. The service is a resource which allows you to run multiple
  # copies of a type of task, and gather up their logs and metrics, as well
  # as monitor the number of running tasks and replace any that have crashed
  Service:
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerRule
    Properties:
      Cluster: accurate-video
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: !Ref "DesiredCount"
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref AnalyzeSG
          Subnets: !Ref PrivateSubnets
      TaskDefinition: !Ref "TaskDefinition"
      LoadBalancers:
        - ContainerName: av-analyze
          ContainerPort: 8080
          TargetGroupArn: !Ref "TargetGroup"
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn
          Port: 8080
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  # A target group. This is used for keeping track of all the tasks, and
  # what IP addresses / port numbers they have. You can query it yourself,
  # to use the addresses yourself, but most often this target group is just
  # connected to an application load balancer, or network load balancer, so
  # it can automatically distribute traffic across all the targets.
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 120
      HealthCheckPath: /api/analyze/audio/async
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 60
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "15"
      Matcher:
        HttpCode: "200,401,400"
      TargetType: ip
      Name: av-analyze
      Port: 8080
      Protocol: HTTP
      UnhealthyThresholdCount: 2
      VpcId: !Ref Vpc
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  # Create a rule on the load balancer for routing traffic to the target group
  LoadBalancerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref "TargetGroup"
          Type: "forward"
      Conditions:
        - Field: path-pattern
          Values: ["/api/analyze/*"]
      ListenerArn: !Ref PublicLoadbalancerListenerArn
      Priority: 1
