AWSTemplateFormatVersion: 2010-09-09
Description: This template will deploy an ECS cluster
Parameters:
  ApplicationTag:
    Type: String
    Description: Used to tag all resources

Resources:
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: accurate-video
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

Outputs:
  ClusterName:
    Description: ECS Cluster Name
    Value: !Ref EcsCluster
