AWSTemplateFormatVersion: 2010-09-09
Description: IAM User for GitLab needed to push images to ECR

Resources:
  IamUser:
    Type: AWS::IAM::User
    Properties: 
      Policies: 
        - PolicyName: GitlabCiUser
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ecr:DescribeImageScanFindings
                  - ecr:StartImageScan
                  - ecr:GetDownloadUrlForLayer
                  - ecr:CompleteLayerUpload
                  - ecr:DescribeImages
                  - ecr:UploadLayerPart
                  - ecr:InitiateLayerUpload
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                Resource: !Sub arn:aws:ecr::${AWS::AccountId}:repository/
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: "*"
      UserName: cm-gitlab-ecr
