AWSTemplateFormatVersion: 2010-09-09
Description: Deploy a service on AWS Fargate, hosted in a private subnet

Parameters:
  AdapterServiceName:
    Type: String
    Description: Adapter Service Name
  ApplicationTag:
    Type: String
    Description: Used to tag all resources
  AuthRunnerSecretArn:
    Type: String
    Description: Auth Runner Secrets Manager Arn
  ClusterName:
    Type: String
    Description: ECS Cluster Name
  ContainerCpu:
    Type: Number
    Description: How much CPU to give the container. 1024 is 1 CPU
  ContainerMemory:
    Type: Number
    Description: How much memory in megabytes to give the container
  DesiredCount:
    Type: Number
    Description: How many copies of the service task to run
  ImageRepoName:
    Type: String
    Description: The docker image repo to use for image deployment
  ImageTag:
    Type: String
    Description: The docker image tag to use for image deployment
  JobsSG:
    Type: String
    Description: Jobs Security Group
  LogGroupName:
    Type: String
    Description: CloudWatch Log Group Name
  PrivateDNSNamespace:
    Type: String
    Description: Private DNS Namespace
  PrivateHostedZoneName:
    Type: String
    Description: Private HostedZone Name
  PrivateSubnets:
    Type: String
    Description: Private Subnets
  VpcCidrBlock:
    Type: String
    Description: VPC CIDR Block

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: av-jobs
      Cpu: !Ref ContainerCpu
      Memory: !Ref ContainerMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: av-jobs
          Cpu: !Ref ContainerCpu
          Memory: !Ref ContainerMemory
          Image: !Sub ${ImageRepoName}:${ImageTag}
          PortMappings:
            - ContainerPort: 5701
            - ContainerPort: 5699
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroupName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: av-jobs
          Environment:
            - Name: AV_RUNNER_LOWRES_TEMPLATE_ID
              Value: !Ref MediaConvertPresetWav
            - Name: AV_RUNNER_AUDIO_EXTRACT_TEMPLATE_ID
              Value: !Ref MediaConvertPresetStandardH264
            - Name: AP_ADAPTER_HOST
              Value: !Sub http://${AdapterServiceName}.${PrivateHostedZoneName}:8080
            - Name: ELEMENTAL_AWS_ROLE
              Value: !GetAtt ElementalRole.Arn
            - Name: HZE_CLUSTER_NAME_REGEXP
              Value: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster\/${ClusterName}
            - Name: HZE_SERVICE_NAME_REGEXP
              Value: !Sub arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:service\/${ClusterName}\/[a-zA-z0-9].*-(JobsService|AdapterService)-.*[a-zA-z0-9]
            - Name: HZE_IPV4_CIDR
              Value: !Ref VpcCidrBlock
          Secrets:
            - Name: AP_ADAPTER_USERNAME
              ValueFrom: !Sub "${AuthRunnerSecretArn}:username::"
            - Name: AP_ADAPTER_PASSWORD
              ValueFrom: !Sub "${AuthRunnerSecretArn}:password::"
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: [sts:AssumeRole]
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref AuthRunnerSecretArn
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: [sts:AssumeRole]
      Path: /
      Policies:
        - PolicyName: AmazonECSTaskRolePolicy
          PolicyDocument:
            Statement:
              - Sid: HazelcastDiscovery
                Effect: Allow
                Action:
                  - ecs:ListClusters
                  - ecs:ListServices
                  - ecs:ListTasks
                  - ecs:DescribeTasks
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:HeadObject
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - rekognition:StartSegmentDetection
                  - rekognition:GetSegmentDetection
                Resource: "*"
              - Effect: Allow
                Action:
                  - sts:PassRole
                Resource:
                  - !GetAtt ElementalRole.Arn
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  ElementalRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [mediaconvert.amazonaws.com]
            Action: [sts:AssumeRole]
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElementalMediaConvertFullAccess
      Policies:
        - PolicyName: ElementalRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:HeadObject
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  DiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: Discovery Service for Hazelcast
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
          - TTL: 60
            Type: SRV
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: jobs
      NamespaceId: !Ref PrivateDNSNamespace
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  JobsService: #NOTE: Do not change resource name
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref JobsSG
          Subnets: !Split [",", !Ref PrivateSubnets]
      PlatformVersion: "1.4.0"
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn
          Port: 5699
      Tags:
        - Key: application
          Value: !Ref ApplicationTag
      TaskDefinition: !Ref TaskDefinition

  MediaConvertPresetStandardH264:
    Type: AWS::MediaConvert::Preset
    Properties:
      Description: Generated by Accurate Video
      Name: accurate_video_standard_h264_follow
      SettingsJson:
        VideoDescription:
          Width: 1920
          ScalingBehavior: DEFAULT
          Height: 1080
          VideoPreprocessors:
            Deinterlacer:
              Algorithm: INTERPOLATE
              Mode: DEINTERLACE
              Control: NORMAL
          TimecodeInsertion: DISABLED
          AntiAlias: ENABLED
          Sharpness: 50
          CodecSettings:
            Codec: H_264
            H264Settings:
              InterlaceMode: PROGRESSIVE
              ParNumerator: 1
              NumberReferenceFrames: 3
              Syntax: DEFAULT
              FramerateDenominator: 1
              GopClosedCadence: 1
              HrdBufferInitialFillPercentage: 90
              GopSize: 90
              Slices: 1
              GopBReference: DISABLED
              HrdBufferSize: 12750000
              SlowPal: DISABLED
              ParDenominator: 1
              SpatialAdaptiveQuantization: ENABLED
              TemporalAdaptiveQuantization: ENABLED
              FlickerAdaptiveQuantization: DISABLED
              EntropyEncoding: CABAC
              Bitrate: 2000000
              FramerateControl: INITIALIZE_FROM_SOURCE
              RateControlMode: CBR
              CodecProfile: HIGH
              Telecine: NONE
              FramerateNumerator: 25
              MinIInterval: 0
              AdaptiveQuantization: HIGH
              CodecLevel: LEVEL_4
              FieldEncoding: PAFF
              SceneChangeDetect: ENABLED
              QualityTuningLevel: MULTI_PASS_HQ
              FramerateConversionAlgorithm: DUPLICATE_DROP
              UnregisteredSeiTimecode: DISABLED
              GopSizeUnits: FRAMES
              ParControl: SPECIFIED
              NumberBFramesBetweenReferenceFrames: 1
              RepeatPps: DISABLED
          AfdSignaling: NONE
          DropFrameTimecode: ENABLED
          RespondToAfd: NONE
          ColorMetadata: INSERT
        AudioDescriptions:
          - AudioTypeControl: FOLLOW_INPUT
            AudioSourceName: Audio Selector 1
            CodecSettings:
              Codec: AAC
              AacSettings:
                AudioDescriptionBroadcasterMix: NORMAL
                Bitrate: 128000
                RateControlMode: CBR
                CodecProfile: LC
                CodingMode: CODING_MODE_2_0
                RawFormat: NONE
                SampleRate: 48000
                Specification: MPEG4
            LanguageCodeControl: FOLLOW_INPUT
            AudioType: 0
        ContainerSettings:
          Container: MP4
          Mp4Settings:
            CslgAtom: INCLUDE
            FreeSpaceBox: EXCLUDE
            MoovPlacement: PROGRESSIVE_DOWNLOAD

  MediaConvertPresetWav:
    Type: AWS::MediaConvert::Preset
    Properties:
      Description: Generated by Accurate Video
      Name: accurate_video_wav
      SettingsJson:
        AudioDescriptions:
          - AudioTypeControl: FOLLOW_INPUT
            AudioSourceName: Audio Selector 1
            CodecSettings:
              Codec: WAV
              WavSettings:
                BitDepth: 16
                Channels: 2
                SampleRate: 44100
                Format: RIFF
            LanguageCodeControl: FOLLOW_INPUT
        ContainerSettings:
          Container: RAW
