AWSTemplateFormatVersion: "2010-09-09"
Description: ""

Parameters:
  ApplicationTag:
    Type: String
    Description: Used to tag all resources

Resources:
  KeycloakSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Accurate Video - Keycloak
      GenerateSecretString:
        SecretStringTemplate: '{"username": "kcadmin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludePunctuation: true
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  BackendSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Accurate Video - Keycloak - Backend"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "backend"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludePunctuation: true
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  AdminSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Accurate Video - Keycloak - Admin"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludePunctuation: true
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

Outputs:
  KeycloakSecret:
    Description: Secrets Manager Secret ARN for Keycloak Backend
    Value: !Ref KeycloakSecret
  BackendSecret:
    Description: Secrets Manager Secret ARN for Keycloak Backend
    Value: !Ref BackendSecret
  AdminSecret:
    Description: Secrets Manager Secret ARN for Keycloak Backend
    Value: !Ref AdminSecret
