AWSTemplateFormatVersion: 2010-09-09
Description: ""

Parameters:
  ApplicationTag:
    Type: String
    Description: Used to tag all resources
    
Resources:
  ElementalRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [mediaconvert.amazonaws.com]
            Action: [sts:AssumeRole]
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElementalMediaConvertFullAccess
      Policies:
        - PolicyName: ElementalRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:HeadObject
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  MediaConvertPresetStandardH264:
    Type: AWS::MediaConvert::Preset
    Properties:
      Description: Generated by Accurate Video
      Name: accurate_video_standard_h264_follow
      SettingsJson:
        VideoDescription:
          Width: 1920
          ScalingBehavior: DEFAULT
          Height: 1080
          VideoPreprocessors:
            Deinterlacer:
              Algorithm: INTERPOLATE
              Mode: DEINTERLACE
              Control: NORMAL
          TimecodeInsertion: DISABLED
          AntiAlias: ENABLED
          Sharpness: 50
          CodecSettings:
            Codec: H_264
            H264Settings:
              InterlaceMode: PROGRESSIVE
              ParNumerator: 1
              NumberReferenceFrames: 3
              Syntax: DEFAULT
              FramerateDenominator: 1
              GopClosedCadence: 1
              HrdBufferInitialFillPercentage: 90
              GopSize: 90
              Slices: 1
              GopBReference: DISABLED
              HrdBufferSize: 12750000
              SlowPal: DISABLED
              ParDenominator: 1
              SpatialAdaptiveQuantization: ENABLED
              TemporalAdaptiveQuantization: ENABLED
              FlickerAdaptiveQuantization: DISABLED
              EntropyEncoding: CABAC
              Bitrate: 2000000
              FramerateControl: INITIALIZE_FROM_SOURCE
              RateControlMode: CBR
              CodecProfile: HIGH
              Telecine: NONE
              FramerateNumerator: 25
              MinIInterval: 0
              AdaptiveQuantization: HIGH
              CodecLevel: LEVEL_4
              FieldEncoding: PAFF
              SceneChangeDetect: ENABLED
              QualityTuningLevel: MULTI_PASS_HQ
              FramerateConversionAlgorithm: DUPLICATE_DROP
              UnregisteredSeiTimecode: DISABLED
              GopSizeUnits: FRAMES
              ParControl: SPECIFIED
              NumberBFramesBetweenReferenceFrames: 1
              RepeatPps: DISABLED
          AfdSignaling: NONE
          DropFrameTimecode: ENABLED
          RespondToAfd: NONE
          ColorMetadata: INSERT
        AudioDescriptions:
          - AudioTypeControl: FOLLOW_INPUT
            AudioSourceName: Audio Selector 1
            CodecSettings:
              Codec: AAC
              AacSettings:
                AudioDescriptionBroadcasterMix: NORMAL
                Bitrate: 128000
                RateControlMode: CBR
                CodecProfile: LC
                CodingMode: CODING_MODE_2_0
                RawFormat: NONE
                SampleRate: 48000
                Specification: MPEG4
            LanguageCodeControl: FOLLOW_INPUT
            AudioType: 0
        ContainerSettings:
          Container: MP4
          Mp4Settings:
            CslgAtom: INCLUDE
            FreeSpaceBox: EXCLUDE
            MoovPlacement: PROGRESSIVE_DOWNLOAD

  MediaConvertPresetWav:
    Type: AWS::MediaConvert::Preset
    Properties:
      Description: Generated by Accurate Video
      Name: accurate_video_wav
      SettingsJson:
        AudioDescriptions:
          - AudioTypeControl: FOLLOW_INPUT
            AudioSourceName: Audio Selector 1
            CodecSettings:
              Codec: WAV
              WavSettings:
                BitDepth: 16
                Channels: 2
                SampleRate: 44100
                Format: RIFF
            LanguageCodeControl: FOLLOW_INPUT
        ContainerSettings:
          Container: RAW

Outputs:
  ElementalRoleArn:
    Description: Elemental Role Arn
    Value: !GetAtt ElementalRole.Arn
  MediaConvertPresetStandardH264:
    Description: MediaConvert Preset Standard H264
    Value: !Ref MediaConvertPresetStandardH264
  MediaConvertPresetWav:
    Description: MediaConvert Preset Wav
    Value: !Ref MediaConvertPresetWav