AWSTemplateFormatVersion: 2010-09-09
Description: ""

Parameters:
  ApplicationTag:
    Type: String
    Description: Used to tag all resources

Resources:
  AuthRunnerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Accurate Video - Adapter - Jobs
      GenerateSecretString:
        SecretStringTemplate: '{"username": "runner"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

Outputs:
  AuthRunnerSecretArn:
    Description: Secrets Manager Secret ARN for the job runner
    Value: !Ref AuthRunnerSecret
