AWSTemplateFormatVersion: 2010-09-09
Description: ""

Parameters:
  ApplicationTag:
    Type: String
    Description: Used to tag all resources
  AdapterSG:
    Type: String
    Description: Adapter Security Group
  CapacityProvider:
    Type: String
    Description: ECS CapacityProvider
    AllowedValues:
      - FARGATE
      - FARGATE_SPOT
  ClusterName:
    Type: String
    Description: ECS Cluster Name
  DesiredCount:
    Type: Number
    Description: How many copies of the service task to run
  LoadbalancerListenerPath:
    Type: String
    Description: Loadbalancer Listener Rule Path
  LoadbalancerListenerPriority:
    Type: String
    Description: Loadbalancer Listener Rule Priority

  PrivateDNSNamespace:
    Type: String
    Description: Private DNS Namespace
  PrivateSubnets:
    Type: String
    Description: Private Subnets
  PublicLoadbalancerListenerArn:
    Type: String
    Description: Public Loadbalancer Listener Arn
  TaskDefinition:
    Type: String
    Description: Task Definition

  Vpc:
    Type: String
    Description: VPC ID
Resources:

  DiscoveryService:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Description: Discovery Service for Hazelcast
      DnsConfig:
        RoutingPolicy: MULTIVALUE
        DnsRecords:
          - TTL: 60
            Type: A
          - TTL: 60
            Type: SRV
      HealthCheckCustomConfig:
        FailureThreshold: 1
      Name: adapter
      NamespaceId: !Ref PrivateDNSNamespace
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  AdapterService: #NOTE: Do not change resource name
    Type: AWS::ECS::Service
    DependsOn: LoadBalancerRule
    Properties:
      CapacityProviderStrategy:
        - Base: 1
          CapacityProvider: !Ref CapacityProvider
          Weight: 1
      Cluster: !Ref ClusterName
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: !Ref DesiredCount
      HealthCheckGracePeriodSeconds: 60
      LoadBalancers:
        - ContainerName: av-adapter
          ContainerPort: 8080
          TargetGroupArn: !Ref TargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref AdapterSG
          Subnets: !Split [",", !Ref PrivateSubnets]
      PlatformVersion: "1.4.0"
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn
          Port: 8080
      Tags:
        - Key: application
          Value: !Ref ApplicationTag
      TaskDefinition: !Ref TaskDefinition

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /api/health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 2
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "15"
      Matcher:
        HttpCode: "200,401"
      TargetType: ip
      Name: av-adapter
      Port: 8080
      Protocol: HTTP
      VpcId: !Ref Vpc
      Tags:
        - Key: application
          Value: !Ref ApplicationTag

  LoadBalancerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      Conditions:
        - Field: path-pattern
          Values: [!Ref LoadbalancerListenerPath]
      ListenerArn: !Ref PublicLoadbalancerListenerArn
      Priority: !Ref LoadbalancerListenerPriority

Outputs:
  ServiceName:
    Description: Service name
    Value: !GetAtt DiscoveryService.Name
